// DO NOT EDIT: This file is autogenerated via the builtin command.

package inputs

import (
	flux "github.com/influxdata/flux"
	ast "github.com/influxdata/flux/ast"
)

func init() {
	flux.RegisterPackage(pkgAST)
}

var pkgAST = &ast.Package{
	BaseNode: ast.BaseNode{
		Errors: nil,
		Loc:    nil,
	},
	Files: []*ast.File{&ast.File{
		BaseNode: ast.BaseNode{
			Errors: nil,
			Loc: &ast.SourceLocation{
				End: ast.Position{
					Column: 16,
					Line:   4,
				},
				File:   "inputs.flux",
				Source: "package inputs\n\nbuiltin fromGenerator\nbuiltin fromSQL",
				Start: ast.Position{
					Column: 1,
					Line:   1,
				},
			},
		},
		Body: []ast.Statement{&ast.BuiltinStatement{
			BaseNode: ast.BaseNode{
				Errors: nil,
				Loc: &ast.SourceLocation{
					End: ast.Position{
						Column: 22,
						Line:   3,
					},
					File:   "inputs.flux",
					Source: "builtin fromGenerator",
					Start: ast.Position{
						Column: 1,
						Line:   3,
					},
				},
			},
			ID: &ast.Identifier{
				BaseNode: ast.BaseNode{
					Errors: nil,
					Loc: &ast.SourceLocation{
						End: ast.Position{
							Column: 22,
							Line:   3,
						},
						File:   "inputs.flux",
						Source: "fromGenerator",
						Start: ast.Position{
							Column: 9,
							Line:   3,
						},
					},
				},
				Name: "fromGenerator",
			},
		}, &ast.BuiltinStatement{
			BaseNode: ast.BaseNode{
				Errors: nil,
				Loc: &ast.SourceLocation{
					End: ast.Position{
						Column: 16,
						Line:   4,
					},
					File:   "inputs.flux",
					Source: "builtin fromSQL",
					Start: ast.Position{
						Column: 1,
						Line:   4,
					},
				},
			},
			ID: &ast.Identifier{
				BaseNode: ast.BaseNode{
					Errors: nil,
					Loc: &ast.SourceLocation{
						End: ast.Position{
							Column: 16,
							Line:   4,
						},
						File:   "inputs.flux",
						Source: "fromSQL",
						Start: ast.Position{
							Column: 9,
							Line:   4,
						},
					},
				},
				Name: "fromSQL",
			},
		}},
		Imports: nil,
		Name:    "inputs.flux",
		Package: &ast.PackageClause{
			BaseNode: ast.BaseNode{
				Errors: nil,
				Loc: &ast.SourceLocation{
					End: ast.Position{
						Column: 15,
						Line:   1,
					},
					File:   "inputs.flux",
					Source: "package inputs",
					Start: ast.Position{
						Column: 1,
						Line:   1,
					},
				},
			},
			Name: &ast.Identifier{
				BaseNode: ast.BaseNode{
					Errors: nil,
					Loc: &ast.SourceLocation{
						End: ast.Position{
							Column: 15,
							Line:   1,
						},
						File:   "inputs.flux",
						Source: "inputs",
						Start: ast.Position{
							Column: 9,
							Line:   1,
						},
					},
				},
				Name: "inputs",
			},
		},
	}},
	Package: "inputs",
	Path:    "inputs",
}
