from(bucket: v.bucket)
  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start:                  |> range(start:
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r[\"_measurement\"] == \"dump1090_recent_aircraft_observed\" or r[\"_measurement\"] == \"dump1090_recent_aircraft_with_multilateration\" or r[\"_measurement\"] == \"dump1090_recent_aircraft_with_position\")
  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)
  |> yield(name: \"last\")
