// DO NOT EDIT: This file is autogenerated via the builtin command.

package math

import ast "github.com/influxdata/flux/ast"

var FluxTestPackages = []*ast.Package{&ast.Package{
	BaseNode: ast.BaseNode{
		Comments: nil,
		Errors:   nil,
		Loc:      nil,
	},
	Files:   []*ast.File{},
	Package: "math_test",
	Path:    "math",
}}
