// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbsemantic

type MonoType = byte

const (
	MonoTypeNONE  MonoType = 0
	MonoTypeBasic MonoType = 1
	MonoTypeVar   MonoType = 2
	MonoTypeArr   MonoType = 3
	MonoTypeRow   MonoType = 4
	MonoTypeFun   MonoType = 5
)

var EnumNamesMonoType = map[MonoType]string{
	MonoTypeNONE:  "NONE",
	MonoTypeBasic: "Basic",
	MonoTypeVar:   "Var",
	MonoTypeArr:   "Arr",
	MonoTypeRow:   "Row",
	MonoTypeFun:   "Fun",
}
