project_name: flux
builds:
  - goos:
    - linux
    - darwin
    goarch:
    - amd64
    - 386
    - arm
    - arm64
    goarm:
    - 6
    - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
    main: ./cmd/flux
    env:
      - GO111MODULE=on
    ldflags: -s -w -X main.commit={{.Commit}}
    binary: flux

archive:
  format: tar.gz
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
  name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}'
  files:
  - LICENSE
  - README.md


release:
  prerelease: auto
  name_template: "v{{.Version}}"

