FROM golang:1.13

ENV PATH="/root/.cargo/bin:${PATH}"
ENV GO111MODULE=on
ENV CGO_ENABLED=1

COPY . /go/src/github.com/influxdata/flux
WORKDIR /go/src/github.com/influxdata/flux

# Install common packages
RUN apt-get clean && apt-get update && \
    apt-get install --no-install-recommends -y \
        clang \
        gcc-arm-linux-gnueabihf \
        gcc-arm-linux-gnueabi \
        gcc-aarch64-linux-gnu \
        gcc-i686-linux-gnu && \
    rm -rf /var/lib/apt/lists/*
RUN go get github.com/influxdata/pkg-config
RUN curl https://sh.rustup.rs -sSf | \
        sh -s -- --default-toolchain stable -y

# XXX: rockstar (13 Feb 2020) - The `-tags` portion of this command can be
# removed when applied to feat/algo-w.
RUN go build -tags 'libflux'
