# This file describes an image that is capable of building Flux.

FROM golang:1.12-alpine

# Note: gcc and libc-dev are only needed since go test -race requires CGO.
RUN apk add --no-cache \
        bash \
        git \
        make \
        gcc \
        libc-dev \
        ruby \
        ragel=6.10-r0
