// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbast

type Assignment = byte

const (
	AssignmentNONE               Assignment = 0
	AssignmentMemberAssignment   Assignment = 1
	AssignmentVariableAssignment Assignment = 2
)

var EnumNamesAssignment = map[Assignment]string{
	AssignmentNONE:               "NONE",
	AssignmentMemberAssignment:   "MemberAssignment",
	AssignmentVariableAssignment: "VariableAssignment",
}
