name: Flux Release
on:
  push:
    tags:
      - v*
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Build and upload release
        uses: ./.github/actions/release
        with:
          ref: '${{github.ref}}'
          repo-token: '${{secrets.GITHUB_TOKEN}}'
        id: release
